cask_args appdir: "/Applications"

tap "homebrew/cask"
tap "homebrew/cask-fonts"

brew "autoconf"
brew "automake"
brew "coreutils"
brew "direnv"
brew "ffmpeg"
brew "git-flow-avh"
brew "gnupg"
brew "hub"
brew "jq"
brew "libtool"
brew "libxslt"
brew "libyaml"
brew "mas"
brew "openssl"
brew "p7zip"
brew "packer"
brew "postgresql"
brew "readline"
brew "rsync"
brew "rustup-init"
brew "ripgrep"
brew "tmux"
brew "unixodbc"
brew "wget"
brew "yadm"
brew "zplug"

cask "1password"
cask "aerial"
cask "alfred"
cask "dash"
cask "displaycal"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "google-backup-and-sync"
cask "iina"
cask "intellij-idea"
cask "iterm2"
cask "macdive"
cask "spotify"

cask "homebrew/cask-fonts/font-source-code-pro"

mas "Amphetamine", id: 937984704
mas "Moom", id: 419330170
mas "The Clock", id: 488764545
