#!/bin/zsh

UNAME_SYSTEM="$(/usr/bin/uname -s)"
UNAME_MACHINE="$(/usr/bin/uname -m)"

if [[ "$UNAME_SYSTEM" == "Linux" ]]; then
  HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew"
elif [[ "$UNAME_SYSTEM" == "Darwin" ]]; then
  if [[ "$UNAME_MACHINE" == "arm64" ]]; then
    # Enable rosetta translation layer
    /usr/bin/xcode-select --install-rosetta
    HOMEBREW_PREFIX="/opt/homebrew"
  else
    HOMEBREW_PREFIX="/usr/local"
  fi
fi

cd $HOME

echo "Init submodules"
yadm submodule update --recursive --init

if [[ "$UNAME_SYSTEM" = "Darwin" ]]; then
  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi
elif [[ "$UNAME_SYSTEM" == "Linux" ]]; then
  if ! command -v brew > /dev/null 2>&1; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi
fi

if [ -f "$HOME/.Brewfile" ]; then
  echo "Updating homebrew bundle"
  $HOMEBREW_PREFIX/bin/brew bundle --global
fi

if [ -f $HOMEBREW_PREFIX/bin/rustup-init ]; then
  $HOMEBREW_PREFIX/bin/rustup-init -q --default-toolchain stable -c rust-src --no-modify-path
  . $HOME/.cargo/env
fi

if [ ! -d $HOME/.zgenom ]; then
  git clone https://github.com/jandamm/zgenom.git "${HOME}/.zgenom"
fi

if [ ! -d $HOME/.asdf ]; then
  git clone https://github.com/asdf-vm/asdf.git $HOME/.asdf
  (cd $HOME/.asdf; git checkout "$(git describe --abbrev=0 --tags)")
fi

. $HOME/.asdf/asdf.sh

$HOME/.asdf/bin/asdf plugin-add golang
$HOME/.asdf/bin/asdf plugin-add java
$HOME/.asdf/bin/asdf plugin-add nodejs
$HOME/.asdf/bin/asdf plugin-add ruby
$HOME/.asdf/bin/asdf plugin-add python

$HOME/.asdf/plugins/nodejs/bin/import-release-team-keyring

if [ -f $HOME/.tool-versions ]; then
  while IFS=' ' read -A tool; do
    asdf install $tool[1] $tool[2]
  done < $HOME/.tool-versions
fi

asdf reshim
