#!/bin/zsh

cd $HOME

echo "Init submodules"
yadm submodule update --recursive --init

if [ "$(uname -s)" = "Darwin" ]; then
  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi
fi

if [ ! $HOME/.asdf ]; then
  git clone https://github.com/asdf-vm/asdf.git $HOME/.asdf
  (cd $HOME/.asdf; git checkout "$(git describe --abbrev=0 --tags)")
fi

. $HOME/.asdf/asdf.sh

$HOME/.asdf/bin/asdf plugin-add golang
$HOME/.asdf/bin/asdf plugin-add java
$HOME/.asdf/bin/asdf plugin-add nodejs
$HOME/.asdf/bin/asdf plugin-add ruby
$HOME/.asdf/bin/asdf plugin-add rust

$HOME/.asdf/plugins/nodejs/bin/import-release-team-keyring

asdf install ruby $(asdf current ruby)
asdf install nodejs $(asdf current nodejs)
asdf install java $(asdf current java)

asdf reshim
